# ticket de validation des conventional commits
name: NF7-DO-03

# déclenchement sur les push only
on: push

jobs:
  affiche_commit:
    runs-on: ubuntu-latest
    steps:
      # affiche le message de commit
      - run: echo "commit = ${{github.event.head_commit.message}} "
  commit_types_matrix_check:
    # teste si le push a lieu sur les branches /features ou /hotfix
    # if: (github.ref == 'refs/heads/features' || github.ref == 'refs/heads/hotfix')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # liste des commit_types autorisés
        commit_types: ["build:", "ci:", "chore:", "docs:", "feat:", "fix:", "perf:", "refactor:", "revert:", "style:", "test:"]
    steps:
      - name: tester qui fait  quoi
        # regarde si le cessage commit commence par un des commit_types autorisés
        if: startsWith( ${{github.event.head_commit.message}}, ${{matrix.commit_types}} )
        run: echo "le commit commence par ${{matrix.commit_types}} ${{github.event.head_commit.message}}, ${{matrix.commit_types}}"